/** Routes: HTML pages, JSON API, subscription hand-off, operator console and dev tools. */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { App } from '../app.ts';
import type { Draft } from '../store/types.ts';
import type { Prefs, Pt } from '../domain/types.ts';
import type { PrefOp } from '../domain/prefs.ts';
import { CATS, depthLabel, FAMILIES, LENS, PRESETS, presetMap, prefsKey, RADII, STATUS_OPTS } from '../domain/prefs.ts';
import { safeEqual, sha256, signValue, verifyValue } from '../lib/crypto.ts';
import * as ob from '../services/onboarding.ts';
import * as rep from '../services/reports.ts';
import { requestOperatorLogin, verifyOperatorLink } from '../services/operators.ts';
import { refreshAll, reviewChange } from '../services/pipeline.ts';
import { runJobs, schedulerTick } from '../jobs/worker.ts';
import { one, many, redirect, Router, send, sendJson } from './html.ts';
import type { Ctx } from './html.ts';
import * as V from './views.ts';
import { devPage, opsPage } from './opsviews.ts';

const UserError = ob.UserError;
const STATIC = new Map([['styles.css', 'text/css; charset=utf-8'], ['app.js', 'text/javascript; charset=utf-8']]);
const PUBLIC_DIR = fileURLToPath(new URL('../../public/', import.meta.url));

export function buildRouter(app: App): Router {
  const r = new Router();
  const page = (c: Ctx, p: V.Page, status = 200) => send(c, status, V.layout(app, p));
  /** Salted, daily-rotating visitor key for rate limits. The IP address itself is never stored. */
  const ipKey = (c: Ctx) => sha256(`${app.cfg.sessionSecret}|${c.ip}|${new Date().toISOString().slice(0, 10)}`).slice(0, 24);
  const draftOf = (c: Ctx) => ob.loadDraft(app, c.cookies.nb_draft);
  const setDraftCookie = (c: Ctx, token: string) => c.setCookie('nb_draft', token, 24 * 3600);
  const maxOf = async (d: Draft) => V.maxStep(d);
  const signPlan = (scope: string, key: string, ops: PrefOp[]) => signValue({ s: scope, k: sha256(key), ops }, app.cfg.sessionSecret);
  const readPlan = (t: string, scope: string, key: string) => { const v = verifyValue<{ s: string; k: string; ops: PrefOp[] }>(t, app.cfg.sessionSecret); return v && v.s === scope && v.k === sha256(key) ? v.ops : null; };

  async function withDraft(c: Ctx, fn: (d: Draft) => Promise<void>) {
    const d = await draftOf(c);
    if (!d) return redirect(c, '/?expired=1');
    if (!d.prefs && !c.url.pathname.startsWith('/start/location')) return redirect(c, '/');
    return fn(d);
  }
  const operatorOf = (c: Ctx) => verifyValue<{ op: string; iat: number }>(c.cookies.nb_op, app.cfg.sessionSecret);
  async function withOperator(c: Ctx, fn: (op: string) => Promise<void>) {
    const v = operatorOf(c);
    if (!v || Date.now() - v.iat > 12 * 3600_000) return redirect(c, '/ops/login');
    return fn(v.op);
  }
  const devOnly = (c: Ctx) => { if (!app.cfg.devTools) { send(c, 404, 'Not found', 'text/plain'); return false; } return true; };

  /* ---------- static, health, legal, status ---------- */
  r.get('/static/:file', (c) => {
    const type = STATIC.get(c.params.file);
    if (!type) return send(c, 404, 'Not found', 'text/plain');
    c.res.setHeader('Cache-Control', 'public, max-age=300');
    send(c, 200, readFileSync(PUBLIC_DIR + c.params.file, 'utf8'), type);
  });
  r.get('/healthz', (c) => sendJson(c, 200, { ok: true, mode: app.cfg.mode, research: app.researcher?.name ?? null }));
  r.get('/status', (c) => page(c, { title: 'Sources and status', body: V.statusPage(app), nav: 'status' }));
  r.get('/legal/:doc', (c) => page(c, { title: c.params.doc === 'terms' ? 'Terms' : 'Privacy', body: V.simplePage(c.params.doc === 'terms' ? 'Terms (draft)' : 'Privacy (draft)', c.params.doc === 'terms'
    ? '<p>These terms are a placeholder. Reports are generated by automated research and may contain errors; check the linked sources before acting on anything.</p>'
    : '<p>We store your address encrypted and use it only to place you on the map and measure distance. The research service receives your neighborhood and a location rounded to about 100 meters, not your street address. Searches and reports are deleted after 24 hours. If you ask to subscribe, we keep your email and filters for the subscription service. The final retention policy needs approval before launch.</p>') }));

  /* ---------- onboarding ---------- */
  r.get('/', async (c) => {
    const d = await draftOf(c);
    const cont = d?.currentReportId ? `<div class="note ok flash">Your last report is ready to view. <a href="/start/report">Open it</a>.</div>` : d?.prefs ? `<div class="note ok flash">You have a search in progress. <a href="/start">Continue it</a>.</div>` : '';
    const expired = c.url.searchParams.get('expired') ? '<div class="note warn flash">Your draft expired after 24 hours and was deleted. Start again below.</div>' : '';
    page(c, { title: "Find out what's changing nearby", body: expired + cont + V.landing(app, {}), nav: 'flow' });
  });
  r.get('/start', async (c) => {
    const d = await draftOf(c);
    if (!d?.prefs) return redirect(c, '/');
    page(c, { title: 'Your location', body: V.locationDone(app, d, await maxOf(d)), nav: 'flow' });
  });
  r.post('/start', async (c) => {
    const q = one(c.form.q);
    const radius = Number(one(c.form.radius)) || 1;
    let d = await draftOf(c);
    if (!d) { const nd = await ob.createDraft(app); d = nd.draft; setDraftCookie(c, nd.token); }
    try {
      const cands = await ob.searchAddress(app, d, q);
      if (d.prefs) { d.prefs.radiusMi = RADII.includes(radius) ? radius : 1; await app.store.saveDraft(d); }
      await app.store.kvSet(`draft-radius:${d.id}`, RADII.includes(radius) ? radius : 1);
      return redirect(c, cands.length === 1 ? `/start/location?c=${encodeURIComponent(cands[0].id)}` : '/start/location');
    } catch (e) {
      if (!(e instanceof UserError)) throw e;
      page(c, { title: "Find out what's changing nearby", body: V.landing(app, { error: e.message, q, radius }), nav: 'flow' }, 422);
    }
  });
  r.get('/start/location', async (c) => withDraft(c, async (d) => {
    if (!d.candidates?.length) return redirect(c, d.prefs ? '/start' : '/');
    const id = c.url.searchParams.get('c');
    const cand = id ? d.candidates.find((x) => x.id === id) : null;
    if (!cand) return page(c, { title: 'Choose your location', body: V.candidatesPage(d.candidates), nav: 'flow' });
    const radius = (await app.store.kvGet<number>(`draft-radius:${d.id}`)) ?? 1;
    if (!cand.covered) return page(c, { title: 'Outside coverage', body: V.outsidePage(app, cand), nav: 'flow' });
    page(c, { title: 'Confirm your location', body: V.confirmPin(app, cand, radius, null), nav: 'flow' });
  }));
  r.post('/start/location/choose', async (c) => withDraft(c, async () => redirect(c, `/start/location?c=${encodeURIComponent(one(c.form.candidate))}`)));
  r.post('/start/location/confirm', async (c) => withDraft(c, async (d) => {
    const cand = d.candidates?.find((x) => x.id === one(c.form.candidate));
    if (!cand) return redirect(c, '/');
    const lng = Number(one(c.form.lng)), lat = Number(one(c.form.lat));
    const adjusted: Pt | undefined = one(c.form.moved) && Number.isFinite(lng) && Number.isFinite(lat) && one(c.form.lng) ? [lng, lat] : undefined;
    const radius = (await app.store.kvGet<number>(`draft-radius:${d.id}`)) ?? 1;
    try {
      const res = await ob.confirmLocation(app, d, cand.id, adjusted, radius);
      if (!res.covered) return page(c, { title: 'Outside coverage', body: V.outsidePage(app, cand), nav: 'flow' });
      redirect(c, '/start/interests');
    } catch (e) {
      if (!(e instanceof UserError)) throw e;
      page(c, { title: 'Confirm your location', body: V.confirmPin(app, cand, radius, null, e.message), nav: 'flow' }, 422);
    }
  }));
  r.post('/start/radius', async (c) => withDraft(c, async (d) => {
    const v = Number(one(c.form.radius));
    if (RADII.includes(v)) { d.prefs!.radiusMi = v; await app.store.saveDraft(d); }
    redirect(c, one(c.form.next) ? '/start/interests' : '/start');
  }));

  r.get('/start/interests', async (c) => withDraft(c, async (d) => page(c, { title: 'Interests', body: V.interestsPage(d, await maxOf(d)), nav: 'flow' })));
  r.post('/start/interests', async (c) => withDraft(c, async (d) => {
    const p = d.prefs!;
    if (one(c.form.all)) p.cats = CATS.map((x) => x.id);
    else if (one(c.form.none)) p.cats = [];
    else p.cats = many(c.form.cats).filter((x) => CATS.some((k) => k.id === x)) as Prefs['cats'];
    if (!one(c.form.all) && !one(c.form.none)) p.evAll = one(c.form.evAll) === '1';
    await app.store.saveDraft(d);
    if (one(c.form.next)) {
      if (!p.cats.length) return page(c, { title: 'Interests', body: V.interestsPage(d, await maxOf(d), 'Choose at least one kind of change to continue.'), nav: 'flow' }, 422);
      return redirect(c, '/start/area');
    }
    redirect(c, '/start/interests');
  }));

  const areaView = async (c: Ctx, d: Draft, error?: string, status = 200) => page(c, { title: 'Area', body: V.areaPage(app, d, await maxOf(d), ob.areaCheck(d.prefs!), error), nav: 'flow' }, status);
  r.get('/start/area', async (c) => withDraft(c, async (d) => {
    if (!d.prefs!.cats.length) return redirect(c, '/start/interests');
    await areaView(c, d);
  }));
  r.post('/start/area', async (c) => withDraft(c, async (d) => {
    const f = c.form, p = d.prefs!;
    const mode = one(f.mode) === 'exclude' ? 'exclude' : 'include';
    try {
      switch (one(f.action)) {
        case 'mode': p.areaMode = one(f.mode) === 'custom' ? 'custom' : 'radius'; await app.store.saveDraft(d); break;
        case 'radius': { const v = Number(one(f.radius)); if (RADII.includes(v)) { p.radiusMi = v; await app.store.saveDraft(d); } break; }
        case 'text': await ob.proposeFromText(app, d, one(f.text)); break;
        case 'neighborhood': await ob.proposeNeighborhood(app, d, mode, one(f.name)); break;
        case 'segment': await ob.proposeSegment(app, d, mode, one(f.road), one(f.from), one(f.to), Number(one(f.width)) || 150); break;
        case 'draw': { let coords: Pt[] = []; try { coords = JSON.parse(one(f.coords) || '[]'); } catch { /* invalid */ } await ob.proposeDrawn(app, d, mode, coords); break; }
        case 'proposal': await ob.resolveProposal(app, d, one(f.id), one(f.apply) === '1'); break;
        case 'remove': await ob.removeShape(app, d, one(f.kind) === 'exc' ? 'exc' : 'inc', Number(one(f.index))); break;
        case 'clarify-dismiss': d.clarify = null; await app.store.saveDraft(d); break;
        case 'next': {
          const blockers = ob.reportBlockers(app, d).filter((b) => /proposed|stretch|larger than/.test(b));
          if (blockers.length) return areaView(c, d, blockers[0], 422);
          return redirect(c, '/start/depth');
        }
      }
      redirect(c, '/start/area');
    } catch (e) {
      if (!(e instanceof UserError)) throw e;
      await areaView(c, d, e.message, 422);
    }
  }));


  r.get('/start/depth', async (c) => withDraft(c, async (d) => page(c, { title: 'Research depth', body: V.depthPage(app, d, await maxOf(d)), nav: 'flow' })));
  r.post('/start/depth', async (c) => withDraft(c, async (d) => {
    const f = c.form, p = d.prefs!;
    const preset = one(f.preset) as keyof typeof PRESETS;
    const boxes = Object.fromEntries(FAMILIES.map((x) => [x.id, many(f.fams).includes(x.id)]));
    const boxesChanged = one(f.custom) && FAMILIES.some((x) => !!p.fams[x.id] !== boxes[x.id]);
    if (app.cfg.research.sources === 'articles') { if (preset in PRESETS) { p.preset = preset; p.fams = presetMap(preset); } }
    else if (preset in PRESETS && PRESETS[preset].name !== depthLabel(p)) { p.preset = preset; p.fams = presetMap(preset); }
    else if (boxesChanged) p.fams = boxes;
    if (one(f.len) in LENS) p.len = one(f.len) as Prefs['len'];
    d.ack = one(f.ack) === '1';
    await app.store.saveDraft(d);
    if (!one(f.next)) return redirect(c, '/start/depth');
    const blockers = ob.reportBlockers(app, d);
    if (blockers.length) return page(c, { title: 'Research depth', body: V.depthPage(app, d, await maxOf(d), blockers[0]), nav: 'flow' }, 422);
    try { await rep.startReport(app, d, ipKey(c)); }
    catch (e) { if (!(e instanceof UserError)) throw e; return page(c, { title: 'Research depth', body: V.depthPage(app, d, await maxOf(d), e.message), nav: 'flow' }, 429); }
    redirect(c, '/start/report');
  }));

  /* ---------- report ---------- */
  const reportView = async (c: Ctx, d: Draft, o: { error?: string; plan?: { diff: any; token: string; message: string | null } | null; text?: string; sub?: { errors?: Record<string, string>; email?: string; sent?: boolean } } = {}, status = 200) => {
    const report = d.currentReportId ? await app.store.getReport(d.currentReportId) : null;
    if (!report) return redirect(c, '/start/depth');
    if (report.status === 'running') return page(c, { title: 'Researching', body: V.progressPage(app, d, report, app.clock.now()), nav: 'flow', refresh: 3 }, status);
    const budget = await rep.reportLimits(app, d, ipKey(c));
    page(c, { title: report.status === 'ready' ? 'Your report' : 'Report problem', body: V.reportPage(app, d, report, { ...o, budget }), nav: 'flow' }, status);
  };
  r.get('/start/report', async (c) => withDraft(c, (d) => reportView(c, d, { sub: c.url.searchParams.get('sent') ? { sent: true } : undefined })));
  r.post('/start/report', async (c) => withDraft(c, async (d) => {
    const f = c.form;
    try {
      switch (one(f.action)) {
        case 'run': await rep.startReport(app, d, ipKey(c)); break;
        case 'refine': {
          const text = one(f.text);
          const plan = await ob.planRefinement(app, d.prefs!, text);
          return reportView(c, d, { text, plan: { diff: plan.diff, token: signPlan(d.id, prefsKey(d.prefs!), plan.ops), message: plan.message } });
        }
        case 'apply': {
          const ops = readPlan(one(f.plan), d.id, prefsKey(d.prefs!));
          if (!ops) throw new UserError('Your settings changed since that proposal. Describe the change again.');
          await ob.applyRefinement(app, d, ops);
          await rep.startReport(app, d, ipKey(c));
          break;
        }
        case 'subscribe': {
          const res = await rep.requestSubscription(app, d, one(f.report), { email: one(f.email), consent: one(f.consent) === '1', marketing: one(f.marketing) === '1' });
          if (!res.ok) return reportView(c, d, { sub: { errors: res.errors, email: one(f.email) } }, 422);
          return redirect(c, '/start/report?sent=1#subscribe');
        }
      }
      redirect(c, '/start/report');
    } catch (e) {
      if (!(e instanceof UserError)) throw e;
      await reportView(c, (await app.store.getDraft(d.id))!, { error: e.message }, 422);
    }
  }));

  /* ---------- subscription confirmation and hand-off ---------- */
  // GET shows a button instead of consuming the token, so email link scanners can't use up the single-use link.
  r.get('/subscribe/confirm', (c) => page(c, { title: 'Confirm', body: V.simplePage('Confirm your request', `<form method="post" action="/subscribe/confirm"><input type="hidden" name="token" value="${(c.url.searchParams.get('token') ?? '').replace(/[^A-Za-z0-9_-]/g, '')}"><button class="btn primary">Confirm</button></form>`) }));
  r.post('/subscribe/confirm', async (c) => {
    const res = await rep.confirmSubscription(app, one(c.form.token));
    if ('error' in res) return page(c, { title: 'Link problem', body: V.confirmPage({ ok: false, message: res.error }) }, 400);
    if (res.handoffUrl) return redirect(c, res.handoffUrl);
    page(c, { title: 'Confirmed', body: V.confirmPage({ ok: true, message: 'Thanks. We saved your area and filters. We’ll email you when weekly subscriptions open, with plans and pricing before you pay anything.' }) });
  });
  /** For the subscription service: read a confirmed request. Bearer SUBSCRIPTION_HANDOFF_SECRET. */
  const handoffAuth = (c: Ctx) => {
    const s = app.cfg.subscribe.handoffSecret;
    const h = String(c.req.headers.authorization ?? '');
    return !!s && h.startsWith('Bearer ') && safeEqual(h.slice(7), s);
  };
  r.get('/api/subscription-requests/:id', async (c) => {
    if (!handoffAuth(c)) return sendJson(c, 401, { error: 'Unauthorized' });
    const x = await app.store.getSubscriptionRequest(c.params.id);
    if (!x || x.status === 'pending_confirmation') return sendJson(c, 404, { error: 'Not found or not confirmed' });
    sendJson(c, 200, x);
  });
  r.post('/api/subscription-requests/:id/handed-off', async (c) => {
    if (!handoffAuth(c)) return sendJson(c, 401, { error: 'Unauthorized' });
    const x = await app.store.getSubscriptionRequest(c.params.id);
    if (!x) return sendJson(c, 404, { error: 'Not found' });
    x.status = 'handed_off';
    await app.store.saveSubscriptionRequest(x);
    sendJson(c, 200, { ok: true });
  });

  /* ---------- operator ---------- */
  r.get('/ops/login', (c) => page(c, { title: 'Operator sign in', body: V.simplePage('Operator sign in', `<form method="post" action="/ops/login" class="stack"><div class="field"><label for="le">Email</label><input type="email" id="le" name="email" autocomplete="email" required></div><div><button class="btn primary">Email me a sign-in link</button></div></form>`) }));
  r.post('/ops/login', async (c) => { await requestOperatorLogin(app, one(c.form.email)); page(c, { title: 'Operator sign in', body: V.simplePage('Check your email', '<p>If that address is an operator, we sent a sign-in link. It works once and expires in 15 minutes.</p>') }); });
  r.get('/ops/verify', (c) => page(c, { title: 'Operator sign in', body: V.simplePage('Sign in', `<form method="post" action="/ops/verify"><input type="hidden" name="token" value="${(c.url.searchParams.get('token') ?? '').replace(/[^A-Za-z0-9_-]/g, '')}"><button class="btn primary">Continue</button></form>`) }));
  r.post('/ops/verify', async (c) => {
    const email = await verifyOperatorLink(app, one(c.form.token));
    if (!email) return page(c, { title: 'Link problem', body: V.simplePage('This link didn’t work', '<p>It expired or was already used. <a href="/ops/login">Request a new one</a>.</p>') }, 400);
    c.setCookie('nb_op', signValue({ op: email, iat: Date.now() }, app.cfg.sessionSecret), 12 * 3600);
    redirect(c, '/ops');
  });
  r.post('/ops/logout', (c) => { c.clearCookie('nb_op'); redirect(c, '/'); });
  r.get('/ops', async (c) => withOperator(c, async (op) => page(c, { title: 'Operator console', body: await opsPage(app, c.url.searchParams.get('tab') ?? 'reports', op, c.url.searchParams.get('ok') ?? undefined), nav: 'ops' })));
  const opAction = (path: string, tab: string, fn: (c: Ctx, op: string) => Promise<string>) => r.post(path, async (c) => withOperator(c, async (op) => {
    try { const msg = await fn(c, op); redirect(c, `/ops?tab=${tab}&ok=${encodeURIComponent(msg)}`); }
    catch (e) { page(c, { title: 'Operator console', body: await opsPage(app, tab, op, undefined, (e as Error).message), nav: 'ops' }, 422); }
  }));
  opAction('/ops/refresh', 'sources', async () => { const res = await refreshAll(app); return `Refreshed ${Object.keys(res).length} feeds.`; });
  opAction('/ops/review', 'records', async (c, op) => { await reviewChange(app, one(c.form.id), one(c.form.decision) === 'approved' ? 'approved' : 'rejected', op); return 'Saved.'; });

  /* ---------- dev tools ---------- */
  r.get('/dev', async (c) => { if (devOnly(c)) page(c, { title: 'Dev tools', body: await devPage(app) }); });
  r.post('/dev/refresh', async (c) => { if (!devOnly(c)) return; await refreshAll(app); redirect(c, '/dev'); });
  r.post('/dev/tick', async (c) => { if (!devOnly(c)) return; await schedulerTick(app); await runJobs(app); redirect(c, '/dev'); });
  r.post('/dev/operator', (c) => { if (!devOnly(c)) return; c.setCookie('nb_op', signValue({ op: 'dev operator', iat: Date.now() }, app.cfg.sessionSecret), 12 * 3600); redirect(c, '/ops'); });

  /* ---------- JSON API ---------- */
  const apiDraft = async (c: Ctx) => {
    const d = await ob.loadDraft(app, c.req.headers['x-draft-token'] as string | undefined);
    if (!d || (c.params.id && d.id !== c.params.id)) { sendJson(c, 404, { error: 'Search not found or expired.' }); return null; }
    return d;
  };
  const apiTry = async (c: Ctx, fn: () => Promise<void>) => { try { await fn(); } catch (e) { if (e instanceof UserError) sendJson(c, 422, { error: e.message }); else throw e; } };
  const draftJson = (d: Draft) => ({ id: d.id, expiresAt: d.expiresAt, candidates: d.candidates?.map(({ point, ...x }) => x) ?? null, prefs: d.prefs, proposals: d.proposals, clarify: d.clarify, runs: d.runs, currentReportId: d.currentReportId });
  r.post('/api/drafts', async (c) => {
    const { draft, token } = await ob.createDraft(app);
    await apiTry(c, async () => {
      if (c.json?.address) await ob.searchAddress(app, draft, String(c.json.address));
      sendJson(c, 201, { token, draft: draftJson(draft) });
    });
  });
  r.post('/api/drafts/:id/resolve-area', async (c) => { const d = await apiDraft(c); if (!d) return; await apiTry(c, async () => {
    if (c.json?.candidateId) { const res = await ob.confirmLocation(app, d, c.json.candidateId, c.json.adjusted, c.json.radiusMi); if (!res.covered) return sendJson(c, 200, { covered: false }); }
    if (c.json?.text) await ob.proposeFromText(app, d, String(c.json.text));
    if (c.json?.proposalId) await ob.resolveProposal(app, d, c.json.proposalId, !!c.json.apply);
    sendJson(c, 200, { draft: draftJson(d), area: d.prefs ? ob.areaCheck(d.prefs) : null });
  }); });
  r.patch('/api/drafts/:id/preferences', async (c) => { const d = await apiDraft(c); if (!d) return; await apiTry(c, async () => {
    const p = ob.requirePrefs(d);
    const j = c.json ?? {};
    const next: Prefs = { ...p };
    if (Array.isArray(j.cats)) next.cats = j.cats.filter((x: string) => CATS.some((k) => k.id === x));
    if (typeof j.evAll === 'boolean') next.evAll = j.evAll;
    if (RADII.includes(j.radiusMi)) next.radiusMi = j.radiusMi;
    if (j.areaMode === 'radius' || j.areaMode === 'custom') next.areaMode = j.areaMode;
    if (j.preset in PRESETS) { next.preset = j.preset; next.fams = presetMap(j.preset); }
    if (j.fams && typeof j.fams === 'object') next.fams = Object.fromEntries(FAMILIES.map((f) => [f.id, !!j.fams[f.id]]));
    if (j.len in LENS) next.len = j.len;
    if (typeof j.statusMin === 'string' && STATUS_OPTS.some((s) => s.v === j.statusMin)) next.statusMin = j.statusMin;
    if (typeof j.ack === 'boolean') d.ack = j.ack;
    await ob.setPrefs(app, d, next);
    sendJson(c, 200, { draft: draftJson(d), blockers: ob.reportBlockers(app, d) });
  }); });
  r.post('/api/drafts/:id/reports', async (c) => { const d = await apiDraft(c); if (!d) return; await apiTry(c, async () => { const x = await rep.startReport(app, d, ipKey(c)); sendJson(c, 202, { id: x.id, status: x.status }); }); });
  r.get('/api/reports/:id', async (c) => {
    const d = await ob.loadDraft(app, c.req.headers['x-draft-token'] as string | undefined);
    const x = await app.store.getReport(c.params.id);
    if (!d || !x || x.draftId !== d.id) return sendJson(c, 404, { error: 'Not found' });
    sendJson(c, 200, { id: x.id, version: x.version, status: x.status, error: x.error, progress: x.progress, summary: x.summary, report: x.issue, dropped: x.dropped, usage: x.usage });
  });

  return r;
}
